table Sales
	lineageTag: b024ce31-8a61-4065-800b-44c327e55ea9

	measure 'Total Sales' = ```
			SUM('Sales'[SalesAmount])
			
			```
		formatString: 0
		lineageTag: a33f436c-005a-4bf9-8e4e-cb326a66823e

	measure 'Total Units Sold' = ```
			SUM('Sales'[Quantity])
			
			```
		formatString: 0
		lineageTag: b0900b61-e87d-49ef-8d70-09542c1692c8

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 98ea139b-8056-4301-9a99-b7ebb2d4a6dc
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: bda4f8ce-3e92-457e-bb8d-472b478b5c66
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 95bc3fc2-de6b-474c-a330-953e969a0b52
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: be7d9b94-28f2-47ca-87ec-a96896505224
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: c8edd790-89ec-49ce-b2a5-c3706b283231
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 653f20b0-b984-43a5-a7fd-fb5910291f2c
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 158886fd-ded8-479e-a95f-5dd817c74aff
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: int64
		formatString: 0
		lineageTag: 390018d4-78c3-4130-94a5-464eb1fcbcb1
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\PaluriManasa\Downloads\OrderDetails_Data\Sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", Int64.Type}, {"DateKey", Int64.Type}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"RegionID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Quantity", Int64.Type}, {"SalesAmount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

